### ISSUE TITLE
[CraftingWithContainers] Feture Reintroduction Request: Inventory First

### ISSUE THREAD

**Issue by Qrylor** [abearcodes/Valheim#18]
In v1.0.4 you removed the option from material removal from player inventory first.  I assume this was to ether fix an issue or possible limitations introduced when switching from directly patching inventory methods directly.

Assuming eventual feasibility, the reintroduction would be vastly appreciated; this is especially true when building with constant changes due to filling up the player inventory with building materials.

Thanks for any information you provided going forward and the ongoing effort to maintain a mod and responding to the community.

**Comment by abearcodes** [comment]
Indeed. Although I do have to say that my patching of the inventory methods in place instead of detouring the methods might be a bad idea too :) Time will tell. 

As for the feature of removing from the player inventory first, nope! There's no limitation on that as the algorithm that removes the items is completely separate from the patches and could be re-added again, it just made the code a bit cleaner and I also didn't hear much in terms of adoption so I decided to cut it.

This is one of those cases where having analytics would really help to know what to focus on, as it might as well be possible you are one of the few people that actually used this "inventory first" functionality :) 

It's a really easy thing to add it back, I'll patch it back in 1.0.8.

**Comment by abearcodes** [comment]
Released in 1.0.8

**Comment by Qrylor** [comment]
Appreciation for reading adding inventory first method.
