### ISSUE TITLE
Mead: Recipes not known or missing entirety

### ISSUE THREAD

**Issue by mattyteds** [abearcodes/Valheim#26]
**Mod**: Simple Recycling

**Mod Version**: 0.0.10

**Describe the bug**
When viewing the RECYCLE tab the following are missing from the list:
 Frost resistance mean
 Fire resistance barley wine
 Medium healing mead
 Poison resistance mead

The following are listed but cannot be recycled because of an unknown recipe:
 Minor healing mead
 Minor stamina mead
 

**How To Reproduce**
1. Put mead in inventory
2. Open recycle tab

**Expected behavior**
I personally think recycling food items is odd so none should be listed, but maybe add an option in the config to toggle listing them.

**Screenshots**
![image](https://user-images.githubusercontent.com/1725926/110675482-eca63c80-81a0-11eb-84c2-76461f0c0e58.png)

**Comment by abearcodes** [comment]
Yeah. Food recycling looks... weird. Deconstructed soup? Nice 😄 I don't have that much time to actually **_play_** Valheim, so it's easy for me to miss these things. 

As for the the undetected recipes.. The way this mod works is that as long as there are recipes for them they should be at least displayed. I just query the in-game ObjectDB recipe list and check those based on the output item. Same goes for the "not known", I reuse the default logic that checks whether or not the player knows that recipe.

Now, the thing is, a fermenter is not considered a "crafting station" object, but a "processor" (like Kilns and Furnaces), so instead of having a recipe, they hold "exchange pairs" that literally say "if X is inserted, return Y".  Hence, you don't see the other meads, and, in theory, you shouldn't be able to see the Minor healing mead and Minor stamina mead. So them appearing is indeed _**weird**_ at first glance, but I do have quite a reasonable explanation for that though :) 

I guess at some point in development the developers intended those two meads to be "craftable" and not acquired via a fermenter, so the recipes are still in the game. Not surprising, it early access and all. I haven't actually started the game and looked at the recipes, this is just based on my knowledge of how things work. 

As for fixing this. The next patch for SimpleRecycling will introduce optional (enabled by default) crafting station requirements (so you can only recycle an Iron Helmet of level 4 on a forge of level 4). It's taking some time because I want all the proper indicators to be in place and for it to feel natural to the grindy and hardcore nature of Valheim (with options to make it less hard ofc). This should fix the issue of soups appearing on random crafting tables, but I guess I'll also introduce a sort of "required crafting station" blacklist so that people who have the crafting station requirement option turned off, can filter out stuff that is made in Cauldrons, for example. 

Thanks for the report!

**Comment by abearcodes** [comment]
Added filter in 0.0.11 that by default excludes recipes coming from the cauldron. Please reopen if you still have issues!
