### ISSUE TITLE
Non-Standard Wood will not be placed in the Kiln

### ISSUE THREAD

**Issue by TheJackalMan** [abearcodes/Valheim#41]
**Mod**: Crafting With Containers

**Mod Version**:  1.0.12

**Describe the bug**
No longer able to pull wood other than Standard Wood in to the Kiln

**How To Reproduce**
1. Have Core or Fine wood in a chest near the Kiln
2. Interact with the Kiln entry point with E
3. Receive message that you do not have the proper materials.

**Expected behavior**
Kiln should take any type of wood

**Comment by abearcodes** [comment]
Hey there, @TheJackalMan! 

A filter for which wood is pulled in was recently added and can be controlled via the `AllowedFuels` setting within the configuration file. It defaults to allowing "normal" wood only. 

Please be aware, than in the next version I will be renaming this variable from `AllowedFuels` to `AllowedKilnFuels` as there is going to be a separate filter for Smelters (the in-game logic is basically that the Kiln "smelts" wood into coal, so that's why the change is needed).

**Comment by abearcodes** [comment]
1.0.13 is out, please update your settings to ignore the Kiln filter again!
