### ISSUE TITLE
Can't see amount of materials from nearby chests

### ISSUE THREAD

**Issue by Kemicaloid** [abearcodes/Valheim#8]
When i go to the crafting station and i try to craft i can see that i'm able to make stuff but the number of materials indicator flashes red saying i have no materials even tho the item itself is highlighted as craftable

I'm using valheim + on my server and i tried to deactivate the "show required items" function but the problem persist.

If i take the items needed in my inventory than it actually show the quantity i have and it still let me craft even if i don't have all the materials in my inventory

If any information is needed let me know
![craftbug](https://user-images.githubusercontent.com/47726636/109416895-49477180-79c1-11eb-8f49-73331ad6d008.jpg)
![craftbug2](https://user-images.githubusercontent.com/47726636/109416904-611ef580-79c1-11eb-9a93-4caa14107bb7.jpg)

**Comment by Kemicaloid** [comment]
The above screenshots are taken with the valheim + function activated, however even if i turn it off the situation is still the same

**Comment by abearcodes** [comment]
Thanks for your report! There is indeed more info you can provide! 

- I suppose this is already the case, but could you please make sure you running the same version on the server and client?
- Do you have any other mods installed? I see that at the very least you have Deposit Items (which should be compatible), but it could be that some other mods completely overwrites the Inventory calls.  
- Can you check please set the setting `DebugViableContainerIndicatorEnabled`  to true and see if the container that holds these items is marked with a "+" sign? 
![image](https://user-images.githubusercontent.com/30690616/109417674-ea83f700-79c4-11eb-8e66-69ee5744ceb2.png)
- Is there any output in the BepInEx console?

**Comment by Kemicaloid** [comment]
Sure

- Did not install on server if i have to be honest, none of the mods i use are on the server ( we playing on a rented server atm)
- I do have a lot of other mods here is the list:

1. craft with containers
2. auto repair
3. build helper
4. clock
5. cooked drops
6. discard inventory items
7. more slots
8. quick deposit
9. remember ip
10. torches eternals
11. use equip in water
12. valheim +

- Yes the chests are marked with the "+" sign
- I do not get anything in the console when i craft stuff even tho it's working (tried both from chests and from inventory items)

I will try to remove all the mods and add em 1 by 1 back to see which one is causing the issue (if that's the case) be back in a few minutes

**Comment by Kemicaloid** [comment]
Ok removed all mods except for yours and valheim +. The problem persist so i think is something connected to v+?

**Comment by abearcodes** [comment]
Indeed. Valheim Plus is known to conflict with many other mods due to how it works. In most places, it overrides completely the method that is supposed to run and instead does it's own logic :( 

For the item count functionality, the CraftingWithContainers mod patches only the line that is responsible for outputting the item count and doesn't touch the rest of the method. It actually still patches it successfully, but Valheim Plus completely reroutes _all_ calls to that method to it's own implementation: 

https://github.com/valheimPlus/ValheimPlus/blob/be6d555d6c37a888ebf6e4259e62572f29639711/ValheimPlus/Hud.cs#L13

Valheim Plus also does not have a way of disabling its patches... It patches everything and then sometimes has methods to override whether or not something is active or not. I know Valheim Plus is a popular mod and brings a lot of benefits, but unless I start detecting and patching Valheim Plus' override, I don't know there is an easy fix :( I do have a couple of ideas of what could make it works, they are hacky, but would ensure that in such cases CraftingWithContainers still works. 

Hopefully at some point Valheim Plus' patches can be enabled and disabled at will.

**Comment by Kemicaloid** [comment]
What i think i can suggest is maybe implement a way to deactivate completely that function on your mod as a toggle? Cause in the previous version i was using of CraftingWithContainers the V+ override was working so the end result was basically the same.

Not sure if i'm asking for something difficult but here is my noob thake on it, anyway glad i could atleast help you understand the issue, i take this chance to say thanks for this mod, is amazing, and this latest version it is even more!

**Comment by abearcodes** [comment]
Valheim Plus actually has a setting to disable the "required items" mod (`showRequiredItems` under `[Hud]`), but the mod doesn't actually do anything about it. 

I'm adding a patch that will remove any patches that would reroute the default SetupRequirements method.  Will release within 30 mins or so as v1.0.5

**Comment by abearcodes** [comment]
Fixed. Please reopen if the issue persists/resurfaces with another mod
